### ISSUE TITLE
Updating the Login activity of the application

### ISSUE THREAD

**Issue by codeahead14** [codeahead14/Android-Git-Client#1]
The application currently has two landing pages -
- If the user is logging for the first time/ logged out, the app launches this [page](https://github.com/codeahead14/Android-Git-Client/blob/Native_Recycler_View/App-Screenshots/Login%20Screen.png).
- If the user is already logged in, the app launches this [page](https://github.com/codeahead14/Android-Git-Client/blob/Native_Recycler_View/App-Screenshots/Repositories%20Overview.png)

The [PreLoginDeciderAcitivity.java](https://github.com/codeahead14/Android-Git-Client/blob/Native_Recycler_View/app/src/main/java/com/example/gaurav/gitfetchapp/PreLoginDeciderActivity.java) implements the decision making for the two cases. However the application has a glitch which is clearly visible whenever the application is launched.

If anyone could do remove that, it would be great!!

Please push the changes to the `Hacktoberfest_Contrib` branch.

**Comment by kartikarora** [comment]
@codeahead14 I would like to work on this!

**Comment by Zweih** [comment]
@codeahead14 Mind if I help?

**Comment by codeahead14** [comment]
Hi @kartikarora Its all yours. Please feel free to make any enhancements, bug fixes and open a PR.
Hi @Zweih Not at all. Please feel free to make any enhancements, bug fixes and open a PR.

**Note: If either of you has forked the repository please update it as I have made some changes to the default branch and bought it back to master.**

**Comment by kartikarora** [comment]
@codeahead14, I was going through the code. I'll give it a try and send a PR asap. You want PR on `master` or some other branch?

**Comment by codeahead14** [comment]
@kartikarora Please push the changes on the `Hacktoberfest_Contrib` branch.
